// This is auto-generated by scripts/downloadReleases.js
define(["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.supportedReleases = [
        "2.4.1",
        "2.7.2",
        "2.8.1",
        "3.0.1",
        "3.1.6",
        "3.3.3",
        "3.5.1",
        "3.6.3",
        "3.7.5",
        "3.8.2"
    ];
});
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicmVsZWFzZXMuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyIuLi8uLi8uLi8uLi9zYW5kYm94L3NyYy9yZWxlYXNlcy50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBQSx3REFBd0Q7Ozs7SUFFM0MsUUFBQSxpQkFBaUIsR0FBRztRQUMvQixPQUFPO1FBQ1AsT0FBTztRQUNQLE9BQU87UUFDUCxPQUFPO1FBQ1AsT0FBTztRQUNQLE9BQU87UUFDUCxPQUFPO1FBQ1AsT0FBTztRQUNQLE9BQU87UUFDUCxPQUFPO0tBQ0MsQ0FBQyIsInNvdXJjZXNDb250ZW50IjpbIi8vIFRoaXMgaXMgYXV0by1nZW5lcmF0ZWQgYnkgc2NyaXB0cy9kb3dubG9hZFJlbGVhc2VzLmpzXG5cbmV4cG9ydCBjb25zdCBzdXBwb3J0ZWRSZWxlYXNlcyA9IFtcbiAgXCIyLjQuMVwiLFxuICBcIjIuNy4yXCIsXG4gIFwiMi44LjFcIixcbiAgXCIzLjAuMVwiLFxuICBcIjMuMS42XCIsXG4gIFwiMy4zLjNcIixcbiAgXCIzLjUuMVwiLFxuICBcIjMuNi4zXCIsXG4gIFwiMy43LjVcIixcbiAgXCIzLjguMlwiXG5dIGFzIGNvbnN0O1xuXG5leHBvcnQgdHlwZSBSZWxlYXNlVmVyc2lvbnMgPVxuICB8IFwiMi40LjFcIlxuICB8IFwiMi43LjJcIlxuICB8IFwiMi44LjFcIlxuICB8IFwiMy4wLjFcIlxuICB8IFwiMy4xLjZcIlxuICB8IFwiMy4zLjNcIlxuICB8IFwiMy41LjFcIlxuICB8IFwiMy42LjNcIlxuICB8IFwiMy43LjVcIlxuICB8IFwiMy44LjJcIjtcbiJdfQ==